services:
  - type: web
    name: globus_vermell
    env: node
    repo: https://github.com/Globus-Vermell/Projecte_de_Innovacio.git
    branch: main
    plan: starter
    region: frankfurt
    numInstances: 1

    buildCommand: npm install
    startCommand: npm start

    autoDeploy: false
    maxShutdownDelaySeconds: 120

    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 3000

      - key: DATABASE_URL
        fromDatabase:
          name: globus_vermell_db
          property: connectionString

      - key: SUPABASE_URL
        value: https://gxsiokjeswgddumssjwj.supabase.co

      - key: SUPABASE_ANON_KEY
        sync: false   # Se define en Render Dashboard
